trigger:
  branches:
    include:
      - master
pr: none  # disable pull request triggers

variables:
- group: pacman-vars
  
- name: MY_APP_LOCATION
  value: "/"  # the apps source files are in the root directory

- name: MY_API_LOCATION  
  value: ""  # no api used

- name: MY_APP_ARTIFACT_LOCATION
  value: "/"  # output artifacts will be placed in the root directory

stages:
- stage: BuildAndDeploy
  displayName: "Build and Deploy"
  
  jobs:
  - job: BuildDeploy
    displayName: "Build and Deploy Job"
    
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true
      fetchTags: true   # ensure that tags are fetched along with the repo

    - script: |
         echo "Checking if the current commit has a tag..."
         TAGS=$(git tag --points-at HEAD)
         if [ -z "$TAGS" ]; then
           echo "No tag found on this commit."
           echo "##vso[task.setvariable variable=shouldDeploy]false"
         else
           echo "Tag(s) found: $TAGS"
           echo "##vso[task.setvariable variable=shouldDeploy]true"
         fi
      name: CheckForTag
      displayName: "Check if commit has a tag"

    - task: AzureStaticWebApp@0
      displayName: "Deploy to Azure Static Web Apps"
      condition: eq(variables.shouldDeploy, 'true')
      inputs:
        app_location: '$(MY_APP_LOCATION)'
        api_location: '$(MY_API_LOCATION)'
        output_location: '$(MY_APP_ARTIFACT_LOCATION)'
        azure_static_web_apps_api_token: '$(pacman-vars)'
